version: '3'
services:
  teste-app:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - postgres-db
      - mongo-db
    ports:
      - "3333:3333"

  postgres-db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  mongo-db:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redisbarber
    ports:
      - "6379:6379"
