version: '3'
services:
  teste-app:
    build: .
    command: yarn dev
    depends_on:
      - db
    ports:
      - "3333:3333"
    environment:
      - DBUSER=postgres
      - DBPASS=psql123
      - DBHOST=db
      - DBNAME=postgres

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: psql123
